ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 512

DESCRIPTION_MAX_LENGTH = 256

ARTICLE_TITLE_MAX_LENGTH = 256
ARTICLE_CONTENT_MAX_LENGTH = 4096

COMMENT_CONTENT_MAX_LENGTH = 1024
